language: ruby
rvm:
- ruby-2.0.0-p353
branches:
  only:
  - master
bundler_args: --without development
cache: bundler

script:
- $TRAVIS_TEST_RESULT
- rspec spec/
- echo $TRAVIS_TEST_RESULT
- if [[ $TRAVIS_TEST_RESULT == 0 ]]; then echo 'sorry failed'; fi
- if [[ $TRAVIS_TEST_RESULT == 0 ]]; then echo 'all good'; fi